### ISSUE TITLE
[Feature Request] Have separate UI tags for when playing Normal vs Hardcore

### ISSUE THREAD

**Issue by HaXrDEV** [Globox1997/Revive#1]
Have separate UI tags for when playing normal vs hardcore.

For example, on my modpack I have modified the UI with FancyMenu to ensure that players understand that clicking the topmost button kills them for good when playing hardcore. 
![image](https://user-images.githubusercontent.com/20630404/173162220-ee7a910c-52a6-4e5c-9d90-c480a9c2ba5e.png)

It would be awesome if it was possible to have those menus be separate depending on whether you are playing in normal survival or hardcore, so that I can have separate messages that makes sense in their respective menus. (An example could be to replace the "Accept your fate" text with "Respawn" or having the red text not appear when playing normal survival)

For my use case you don't even have to change anything about the menu's themselves, just that they are separate in the code so that it is possible to customize them individually. 

Hope this makes sense to you 😃

**Comment by Globox1997** [comment]
hey HaXrBOT,
I think Minecraft itself handles this already pretty good since by default the main button is called "Spectate World" instead of "Respawn"

**Comment by HaXrDEV** [comment]
Yep i completely agree. I realized this as well sometime after posting, which is why i marked it as completed.
