### ISSUE TITLE
Suggestion: Add a config option that makes it so you could revive another player without a potion

### ISSUE THREAD

**Issue by Slimation** [Globox1997/Revive#2]
Add a config option that makes it so you could revive another player without a potion with instead the downed player being able to revive when another player is near their corpse as some players find it tedious to make a potion and would just prefer to have the option the option to revive a player without one especially in the early game.

**Comment by thedeerirty** [comment]
I second this

**Comment by Ozakinn** [comment]
Up on this one

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/Revive/commit/514244b84bb4fe6512f25ad29418ec8dfbc90b8e](https://github.com/Globox1997/Revive/commit/514244b84bb4fe6512f25ad29418ec8dfbc90b8e)
